version: "3.7"
services:
  db-test:
    image: postgres:latest
    container_name: db_test_aggreco
    restart: always
    expose:
      - 5433
    ports:
      - 5433:5433
    environment:
      - POSTGRES_PORT=5433
      - POSTGRES_USER=admin_test
      - POSTGRES_PASSWORD=admin_test
      - POSTGRES_DB=document_test
      - PGPORT=5433