"""empty message

Revision ID: 1a10ec5793ee
Revises: 35654d849e5d
Create Date: 2025-08-17 12:47:46.295886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a10ec5793ee'
down_revision: Union[str, None] = '35654d849e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            ALTER TABLE claim 
            ALTER COLUMN blueprint_json_file 
            TYPE JSONB 
            USING blueprint_json_file::jsonb;
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
           ALTER TABLE claim 
           ALTER COLUMN blueprint_json_file 
           TYPE TEXT;
       """)
    # ### end Alembic commands ###
