"""empty message

Revision ID: 33f504f96ad7
Revises: 1a10ec5793ee
Create Date: 2025-09-29 12:16:46.318801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f504f96ad7'
down_revision: Union[str, None] = '1a10ec5793ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blueprint', sa.Column('is_delite', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('claim', sa.Column('is_delite', sa.Boolean(), server_default='False', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim', 'is_delite')
    op.drop_column('blueprint', 'is_delite')
    # ### end Alembic commands ###
