"""empty message

Revision ID: 35654d849e5d
Revises: a4f45c4ed627
Create Date: 2025-08-17 12:06:42.898576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35654d849e5d'
down_revision: Union[str, None] = 'a4f45c4ed627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('id_equipment', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'claim', 'equipment', ['id_equipment'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'claim', type_='foreignkey')
    op.drop_column('claim', 'id_equipment')
    # ### end Alembic commands ###
