"""empty message

Revision ID: 4bee9320b9ff
Revises: 33f504f96ad7
Create Date: 2025-09-29 21:58:18.309785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bee9320b9ff'
down_revision: Union[str, None] = '33f504f96ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_blueprint', sa.Column('is_delite', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('type_equipment', sa.Column('is_delite', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('type_equipment_blueprint', sa.Column('is_delite', sa.Boolean(), server_default='False', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type_equipment_blueprint', 'is_delite')
    op.drop_column('type_equipment', 'is_delite')
    op.drop_column('type_blueprint', 'is_delite')
    # ### end Alembic commands ###
