"""empty message

Revision ID: 6816ad16cd1f
Revises: 4bee9320b9ff
Create Date: 2025-09-30 19:58:48.412141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6816ad16cd1f'
down_revision: Union[str, None] = '4bee9320b9ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profession', sa.Column('is_delite', sa.Boolean(), server_default='False', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profession', 'is_delite')
    # ### end Alembic commands ###
