"""empty message

Revision ID: 87ec7c687bf4
Revises: ddf548dde240
Create Date: 2025-07-26 13:32:28.111134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ec7c687bf4'
down_revision: Union[str, None] = 'ddf548dde240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('system_name')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('date_check_last', sa.DateTime(), nullable=False),
    sa.Column('date_check_next', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_type'], ['type_device.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    op.drop_table('type_device')
    # ### end Alembic commands ###
