"""empty message

Revision ID: 8da394fd2f0a
Revises: ddec71cc39ed
Create Date: 2025-07-19 18:00:26.725602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da394fd2f0a'
down_revision: Union[str, None] = 'ddec71cc39ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blueprint', sa.Column('last_datetime_edit', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blueprint', 'last_datetime_edit')
    # ### end Alembic commands ###
