"""empty message

Revision ID: a4f45c4ed627
Revises: bbec2bea1048
Create Date: 2025-08-17 12:00:03.983753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4f45c4ed627'
down_revision: Union[str, None] = 'bbec2bea1048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('name', sa.String(), server_default='template', nullable=True))
    op.add_column('claim', sa.Column('blueprint_xlsx_file', sa.String(), nullable=True))
    op.add_column('claim', sa.Column('blueprint_json_file', sa.String(), nullable=True))
    op.alter_column('claim', 'datetime',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claim', 'datetime',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('claim', 'blueprint_json_file')
    op.drop_column('claim', 'blueprint_xlsx_file')
    op.drop_column('claim', 'name')
    # ### end Alembic commands ###
