"""empty message

Revision ID: ddec71cc39ed
Revises: 
Create Date: 2025-07-19 13:40:45.073926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddec71cc39ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profession',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('system_name')
    )
    op.create_table('state_claim',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('system_name')
    )
    op.create_table('type_blueprint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('system_name')
    )
    op.create_table('type_equipment',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('system_name')
    )
    op.create_table('type_equipment_blueprint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('system_name')
    )
    op.create_table('type_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('system_name')
    )
    op.create_table('blueprint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id_plant', sa.Integer(), nullable=False),
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('path_template_docx_file', sa.String(), nullable=False),
    sa.Column('path_map_data_json_file', sa.String(), nullable=False),
    sa.Column('path_form_xlsx_file', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_plant'], ['type_equipment_blueprint.id'], ),
    sa.ForeignKeyConstraint(['id_type'], ['type_blueprint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('id_profession', sa.Integer(), nullable=False),
    sa.Column('painting', sa.String(), nullable=True),
    sa.Column('is_delite', sa.Boolean(), server_default='False', nullable=True),
    sa.ForeignKeyConstraint(['id_profession'], ['profession.id'], ),
    sa.ForeignKeyConstraint(['id_type'], ['type_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('claim',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id_state_claim', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('main_document', sa.String(), nullable=True),
    sa.Column('edit_document', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('last_datetime_edit', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_state_claim'], ['state_claim.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim')
    op.drop_table('user')
    op.drop_table('blueprint')
    op.drop_table('type_user')
    op.drop_table('type_equipment_blueprint')
    op.drop_table('type_equipment')
    op.drop_table('type_blueprint')
    op.drop_table('state_claim')
    op.drop_table('profession')
    # ### end Alembic commands ###
