"""empty message

Revision ID: ddf548dde240
Revises: 8da394fd2f0a
Create Date: 2025-07-19 18:09:46.109447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf548dde240'
down_revision: Union[str, None] = '8da394fd2f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blueprint', sa.Column('uuid', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'blueprint', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blueprint', type_='unique')
    op.drop_column('blueprint', 'uuid')
    # ### end Alembic commands ###
