"""empty message

Revision ID: ee0907604d00
Revises: 87ec7c687bf4
Create Date: 2025-07-27 13:43:07.568484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0907604d00'
down_revision: Union[str, None] = '87ec7c687bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('id_blueprint', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'claim', 'blueprint', ['id_blueprint'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'claim', type_='foreignkey')
    op.drop_column('claim', 'id_blueprint')
    # ### end Alembic commands ###
